language: php

php:
    - 7.0

install:
    - composer install --dev --no-interaction --prefer-source
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover