language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install:
    - composer install --dev
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover