language: php

php:
    - 7.0

sudo: false

before_install:
  - composer selfupdate

install:
    - composer install --dev --no-interaction --prefer-dist
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover