imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    locales: [fr, en]
    database_prefix: fop_
    app_name: "FOP"
    app_version: "0.0.2"
    mail_noreply: "noreply@fop.wtf"
    mail_admin: "postmaster@fop.wtf"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:      ['bootstrap_3_layout.html.twig']
    globals:
        app_name:    "%app_name%"
        app_version: "%app_version%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:         pdo_pgsql
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        UTF8
        server_version: 9.3.9
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode:  "%mailer_auth_mode%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

# Routing Configuration
jms_i18n_routing:
    default_locale: "%locale%"
    locales:        "%locales%"
    strategy:       prefix

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
    from_email:
        address:        "%mail_noreply%"
        sender_name:    "%app_name%"

# Gravatar Configuration
ornicar_gravatar: ~

# KnpMenu Configuration
knp_menu:
    twig:
        template: :menu:bootstrap.html.twig

# Navigation Configuration
rollerworks_navigation:
    menus:
        main:
            items:
                home:
                    label: navigation.main.home
                    route: { name: homepage }
                calendar:
                    label: navigation.main.calendar
                    route: { name: season_races, parameters: { year: 2016 } }
                calendar:
                    label: navigation.main.teams
                    route: { name: season_teams, parameters: { year: 2016 } }
                standings:
                    label: navigation.main.standings
                    items:
                        user:
                            label: navigation.main.user_standings
                            route: { name: season_user_standings, parameters: { year: 2016 } }
                        driver:
                            label: navigation.main.driver_standings
                            route: { name: season_driver_standings, parameters: { year: 2016 } }
                        constructor:
                            label: navigation.main.constructor_standings
                            route: { name: season_constructor_standings, parameters: { year: 2016 } }
        sign:
            items:
                login:
                    label: navigation.sign.in
                    route: { name: fos_user_security_login }
                register:
                    label: navigation.sign.up
                    route: { name: fos_user_registration_register }
        user:
            items:
                account:
                    label: navigation.user.account
                    route: { name: homepage }
                logout:
                    label: navigation.user.logout
                    route: { name: fos_user_security_logout }
        footer:
            items:
                contact:
                    label: navigation.footer.contact
                    uri:   "mailto:%mail_noreply%"