imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locales: [fr, en]
    database_prefix: fop_
    app_name: "FOP"
    mail_noreply: "noreply@fop.com"

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Routing Configuration
jms_i18n_routing:
    default_locale: "%locale%"
    locales:        "%locales%"
    strategy:       prefix

# Tanslation Configuration
jms_translation:
    source_language:         "%locale%"
    locales:                 "%locales%"
    configs:
        app:
            dirs:            ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir:      "%kernel.root_dir%/Resources/translations"
            ignored_domains: ["routes"]
            excluded_names:  ["*TestCase.php", "*Test.php"]
            excluded_dirs:   ["var"]
            output_format:   xliff

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        confirmation:
            enabled:    true

# Gravatar Configuration
ornicar_gravatar: ~

# KnpMenu Configuration
knp_menu:
    twig:
        template: :menu:bootstrap.html.twig

# EsayAdmin Configuration
easy_admin:
    entities:
        - AppBundle\Entity\Circuit
        - AppBundle\Entity\Constructor
        - AppBundle\Entity\Driver
        - AppBundle\Entity\FinishingPosition
        - AppBundle\Entity\Prediction
        - AppBundle\Entity\Race
        - AppBundle\Entity\ScoringSystem
        - AppBundle\Entity\Season
        - AppBundle\Entity\Team
        - AppBundle\Entity\User
