# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Twig
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    # Translation
    translation.menu_extractor:
        class: AppBundle\Translation\MenuTranslationExtractor
        tags:
            - name: jms_translation.file_visitor

    # Repositories
    repository.user:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [AppBundle:User]
    repository.circuit:
        class: AppBundle\Repository\CircuitRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [AppBundle:Circuit]
    repository.driver:
        class: AppBundle\Repository\DriverRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [AppBundle:Driver]
    repository.consturctor:
        class: AppBundle\Repository\ConstructorRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [AppBundle:Constructor]

    # Services
    service.user:
        class: AppBundle\Service\UserService
        arguments: ["@repository.user"]
    service.circuit:
        class: AppBundle\Service\CircuitService
        arguments: ["@repository.circuit"]
    service.driver:
        class: AppBundle\Service\DriverService
        arguments: ["@repository.driver"]
    service.constructor:
        class: AppBundle\Service\ConstructorService
        arguments: ["@repository.consturctor"]

    # Menus
    menu_builder:
        class: AppBundle\Menu\Builder
        scope: request
        arguments: ["@knp_menu.factory", "@request_stack"]
    menu_main:
         class: Knp\Menu\MenuItem
         factory_service: menu_builder
         factory_method: createMainMenu
         tags:
             - { name: knp_menu.menu, alias: main }
    menu_footer:
         class: Knp\Menu\MenuItem
         factory_service: menu_builder
         factory_method: createFooterMenu
         tags:
             - { name: knp_menu.menu, alias: footer }
    menu_user:
         class: Knp\Menu\MenuItem
         factory_service: menu_builder
         factory_method: createUserMenu
         arguments: ["@security.authorization_checker"]
         tags:
             - { name: knp_menu.menu, alias: user }
    menu_locale_switcher:
         class: Knp\Menu\MenuItem
         factory_service: menu_builder
         factory_method: createLocaleSwitcherMenu
         arguments: ["%locales%"]
         tags:
             - { name: knp_menu.menu, alias: locale_switcher }
